# Generated by Django 4.2.10 on 2024-04-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_rename_text_review_comment_movie_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='posters',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
