# Generated by Django 4.2.10 on 2024-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_movie_posters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='posters',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.FileField(default='leo.jpg', upload_to='posters'),
        ),
    ]
