# Generated by Django 4.2.10 on 2024-04-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_remove_movie_posters_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.FileField(default='leo.jpeg', upload_to='posters'),
        ),
    ]
